---
mappings:
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/current/endur/dl130_market_risk_stage_result_summary"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/current/endur/dl130_market_risk_stage_result_summary"
  rid: "ri.foundry.lava-catalog.dataset.9dfe2715-b0e8-430f-8d8c-03204dace35d"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/current/freeport/fp_gas_m0145"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/current/freeport/fp_gas_m0145"
  rid: "ri.foundry.lava-catalog.dataset.cb11dc11-5969-466e-8e1d-5fcf22d1b101"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/current/freeport/fp_power_m01015"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/current/freeport/fp_power_m01015"
  rid: "ri.foundry.lava-catalog.dataset.e05a0585-eb6e-4d1f-b16e-a002b8dee1f4"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/current/titan/tr200_exposure"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/current/titan/tr200_exposure"
  rid: "ri.foundry.lava-catalog.dataset.f5611b8a-5206-4c4f-974a-67749d211250"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/LNG_combined_exposure"
  modes:
  - "BUILD"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/LNG_combined_exposure"
  rid: "ri.foundry.lava-catalog.dataset.be92f9f9-b650-4abe-b29d-c14039a3466d"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/LNG_combined_exposure_FAST"
  modes:
  - "BUILD"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/LNG_combined_exposure_FAST"
  rid: "ri.foundry.lava-catalog.dataset.ee838a78-4d64-4ad7-a49d-5d19e1f52e6b"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/dl130_Endur_Monthly_Exposure_combined_format"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/dl130_Endur_Monthly_Exposure_combined_format"
  rid: "ri.foundry.lava-catalog.dataset.1b49789f-a75a-4a4b-b575-5c976fc887c8"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/dl130_market_risk_stage_result_summary_conformed"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/dl130_market_risk_stage_result_summary_conformed"
  rid: "ri.foundry.lava-catalog.dataset.1dc4d996-223d-4d80-9c00-139ed798b666"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/dl130_market_risk_stage_result_summary_monthly"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/dl130_market_risk_stage_result_summary_monthly"
  rid: "ri.foundry.lava-catalog.dataset.9139c159-a35e-4423-a781-46654a5f12cc"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/fp_gas_m0145_cleansed"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/fp_gas_m0145_cleansed"
  rid: "ri.foundry.lava-catalog.dataset.cba57fd6-10cb-40cf-a8b0-5389983183b3"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/fp_gas_m0145_combined_format"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/fp_gas_m0145_combined_format"
  rid: "ri.foundry.lava-catalog.dataset.0ab0cedb-bd2d-4c3d-8cea-aff1629eebfc"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/fp_power_m01015_cleansed"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/fp_power_m01015_cleansed"
  rid: "ri.foundry.lava-catalog.dataset.1a244a0b-3157-4878-ba97-f5a553c559d2"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/fp_power_m01015_combined_format"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/fp_power_m01015_combined_format"
  rid: "ri.foundry.lava-catalog.dataset.d00b9f6c-b597-46c0-92d8-160444ab21ce"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/tr200_combined_format"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/tr200_combined_format"
  rid: "ri.foundry.lava-catalog.dataset.5b031bf5-35e3-4f0d-b2c5-d31747d3da0c"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/tr200_exposure_conformed"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/transformed/tr200_exposure_conformed"
  rid: "ri.foundry.lava-catalog.dataset.b97a97a1-bbc8-4f1b-a557-650abf6ca65a"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/typed/endur/dl130_market_risk_stage_result_summary"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/typed/endur/dl130_market_risk_stage_result_summary"
  rid: "ri.foundry.lava-catalog.dataset.d23686e3-de62-41a8-ae7f-3e167db5d76a"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/typed/freeport/fp_gas_m0145"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/typed/freeport/fp_gas_m0145"
  rid: "ri.foundry.lava-catalog.dataset.f811f894-958d-4a75-8baf-e6aa0de277b8"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/typed/freeport/fp_power_m01015"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/typed/freeport/fp_power_m01015"
  rid: "ri.foundry.lava-catalog.dataset.0f4adedd-11f1-4630-a95a-d8c5ed4208ba"
- alias: "/BP/IST-IG-DD/data/technical/exposure_java/typed/titan/tr200_exposure"
  modes:
  - "BUILD"
  - "READ"
  path: "/BP/IST-IG-DD/data/technical/exposure_java/typed/titan/tr200_exposure"
  rid: "ri.foundry.lava-catalog.dataset.45f7905e-f983-4001-ac98-ef028a4cc834"
- alias: "/BP/IST-IG-SS-Systems/data/raw/endur/dl130_market_risk_stage_result_summary/dl130_market_risk_stage_result_summary"
  modes:
  - "READ"
  path: "/BP/IST-IG-SS-Systems/data/raw/endur/dl130_market_risk_stage_result_summary/dl130_market_risk_stage_result_summary"
  rid: "ri.foundry.lava-catalog.dataset.55eb869d-e1f1-4b25-85ef-850b00b8c2b2"
- alias: "/BP/IST-IG-SS-Systems/data/raw/freeport/fp_gas_m0145/fp_gas_m0145"
  modes:
  - "READ"
  path: "/BP/IST-IG-SS-Systems/data/raw/freeport/fp_gas_m0145/fp_gas_m0145"
  rid: "ri.foundry.lava-catalog.dataset.4f1af8a8-9c7a-4a2d-869d-e97e8ce11554"
- alias: "/BP/IST-IG-SS-Systems/data/raw/freeport/fp_power_m01015/fp_power_m01015"
  modes:
  - "READ"
  path: "/BP/IST-IG-SS-Systems/data/raw/freeport/fp_power_m01015/fp_power_m01015"
  rid: "ri.foundry.lava-catalog.dataset.8d9a5e8a-0c34-4b86-af6b-a7fe8dca38b4"
- alias: "/BP/IST-IG-SS-Systems/data/raw/titan/tr200_exposure/tr200_exposure"
  modes:
  - "READ"
  path: "/BP/IST-IG-SS-Systems/data/raw/titan/tr200_exposure/tr200_exposure"
  rid: "ri.foundry.lava-catalog.dataset.ddaa7fd6-b160-4053-9d1e-db5f3348de93"
- alias: "/BP/IST-IG-SS-Systems/data/refdata/conversion_uom_pivotted"
  modes:
  - "READ"
  path: "/BP/IST-IG-SS-Systems/data/refdata/conversion_uom_pivotted"
  rid: "ri.foundry.lava-catalog.dataset.08a1bcee-30ae-452c-aeec-b2a30afbe90b"
- alias: "/BP/IST-IG-UC-User-Data/data/referencedata/Conformed_Units"
  modes:
  - "READ"
  path: "/BP/IST-IG-UC-User-Data/data/referencedata/Conformed_Units"
  rid: "ri.foundry.lava-catalog.dataset.5b96ed34-9a9f-42a2-83b3-3f403bf8aa9d"
- alias: "/BP/IST-IG-UC-User-Data/data/referencedata/Endur_Counterparties"
  modes:
  - "READ"
  path: "/BP/IST-IG-UC-User-Data/data/referencedata/Endur_Counterparties"
  rid: "ri.foundry.lava-catalog.dataset.d7a859b8-13f3-4cd1-beb3-2e14c2469932"
- alias: "/BP/IST-IG-UC-User-Data/data/referencedata/Endur_Curves"
  modes:
  - "READ"
  path: "/BP/IST-IG-UC-User-Data/data/referencedata/Endur_Curves"
  rid: "ri.foundry.lava-catalog.dataset.f1adba1b-22f0-4ee2-902c-4c6e8d853f22"
- alias: "/BP/IST-IG-UC-User-Data/data/referencedata/Endur_Options_Curves"
  modes:
  - "READ"
  path: "/BP/IST-IG-UC-User-Data/data/referencedata/Endur_Options_Curves"
  rid: "ri.foundry.lava-catalog.dataset.4243be67-691e-46bc-9e79-8ec2d6fb142a"
- alias: "/BP/IST-IG-UC-User-Data/data/referencedata/NAGP_Counterparties"
  modes:
  - "READ"
  path: "/BP/IST-IG-UC-User-Data/data/referencedata/NAGP_Counterparties"
  rid: "ri.foundry.lava-catalog.dataset.405c8907-285a-415d-a518-2a63d3ceb870"
- alias: "/BP/IST-IG-UC-User-Data/data/referencedata/NAGP_Curves"
  modes:
  - "READ"
  path: "/BP/IST-IG-UC-User-Data/data/referencedata/NAGP_Curves"
  rid: "ri.foundry.lava-catalog.dataset.64dd5849-b10f-49e5-98de-c932948e337c"
- alias: "/BP/IST-IG-UC-User-Data/data/referencedata/NAGP_UOMs"
  modes:
  - "READ"
  path: "/BP/IST-IG-UC-User-Data/data/referencedata/NAGP_UOMs"
  rid: "ri.foundry.lava-catalog.dataset.f3aed1dc-3513-410b-b7c6-574e842eaf50"
- alias: "/BP/IST-IG-UC-User-Data/data/referencedata/Titan_Curves"
  modes:
  - "READ"
  path: "/BP/IST-IG-UC-User-Data/data/referencedata/Titan_Curves"
  rid: "ri.foundry.lava-catalog.dataset.9f898385-e887-4e83-bd75-dd1c6461abf2"
- alias: "/BP/IST-IG-UC-User-Data/data/referencedata/Titan_Oil_UOM_Conversions"
  modes:
  - "READ"
  path: "/BP/IST-IG-UC-User-Data/data/referencedata/Titan_Oil_UOM_Conversions"
  rid: "ri.foundry.lava-catalog.dataset.93f49521-6c1e-41f8-a666-b380aa0b3da2"
- alias: "/BP/IST-IG-UC-User-Data/data/referencedata/UOM_Conversions"
  modes:
  - "READ"
  path: "/BP/IST-IG-UC-User-Data/data/referencedata/UOM_Conversions"
  rid: "ri.foundry.lava-catalog.dataset.7c41c9ce-8440-42f1-819b-53d6c12b43e6"
