from pyspark.sql.types import StructField, StructType, StringType, DoubleType, IntegerType, DateType, TimestampType

typed_output_schema = StructType([
        StructField('Run_Datetime', TimestampType(), True, {}),
        StructField('Reval_Date', DateType(), True, {}),
        StructField('Portfolio', StringType(), True, {}),
        StructField('Currency', StringType(), True, {}),
        StructField('Ins_Type', StringType(), True, {}),
        StructField('dtd_pnl_disc_total_pflo_ccy', DoubleType(), True, {}),
        StructField('Variance', DoubleType(), True, {}),
        StructField('Impact_of_Delta', DoubleType(), True, {}),
        StructField('Impact_of_Gamma', DoubleType(), True, {}),
        StructField('Impact_of_Vega', DoubleType(), True, {}),
        StructField('Theta', DoubleType(), True, {}),
        StructField('Impact_of_resets_Phys', DoubleType(), True, {}),
        StructField('Impact_of_resets_Cash', DoubleType(), True, {}),
        StructField('New_Trade_PNL_Other', DoubleType(), True, {}),
        StructField('New_Trade_PNL_Day_Ahead', DoubleType(), True, {}),
        StructField('New_Trade_PNL_Within_Day', DoubleType(), True, {}),
        StructField('Impact_of_Amendments', DoubleType(), True, {}),
        StructField('Impact_of_Cancellations', DoubleType(), True, {}),
        StructField('Impact_of_Closeouts', DoubleType(), True, {}),
        StructField('Impact_of_Volume_Change', DoubleType(), True, {}),
        StructField('Impact_of_Spot_FX', DoubleType(), True, {}),
        StructField('Impact_of_Vega_Gamma', DoubleType(), True, {}),
        StructField('Impact_of_Cross_Gamma', DoubleType(), True, {}),
        StructField('Impact_of_Cross_Vega_Gamma', DoubleType(), True, {}),
        StructField('Impact_of_Exercise_Option', DoubleType(), True, {}),
        StructField('Impact_of_Rho', DoubleType(), True, {}),
        StructField('Impact_of_Delta_Shape', DoubleType(), True, {}),
        StructField('Shaped_Deal', StringType(), True, {}),
        StructField('impact_option_expiry', DoubleType(), True, {}),
        StructField('impact_of_reset_tac_delta', DoubleType(), True, {}),
        StructField('impact_of_delta_pwr_fut_da', DoubleType(), True, {}),
        StructField('impact_of_df_delta', DoubleType(), True, {}),
])


transformed_output_schema = StructType([
        StructField('Valuation_Date', DateType(), True, {'from': 'Reval_Date'}),
        StructField('Portfolio', StringType(), True, {}),
        StructField('Portfolio_Currency', StringType(), True, {'from': 'Currency'}),
        StructField('Instrument_Type', StringType(), True, {'from': 'Ins_Type'}),
        StructField('Dtd_Total_Pf', DoubleType(), True, {'rounding': '0', 'from': 'dtd_pnl_disc_total_pflo_ccy'}),
        StructField('Variance', DoubleType(), True, {}),
        StructField('Impact_Of_Delta', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Delta'}),
        StructField('Impact_Of_Gamma', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Gamma'}),
        StructField('Impact_Of_Vega', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Vega'}),
        StructField('Theta', DoubleType(), True, {'rounding': '0'}),
        StructField('Impact_Of_Resets_Phys', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_resets_Phys'}),
        StructField('Impact_Of_Resets_Cash', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_resets_Cash'}),
        StructField('New_Trade_Pnl_Other', DoubleType(), True, {'rounding': '0', 'from': 'New_Trade_PNL_Other'}),
        StructField('New_Trade_Pnl_Day_Ahead', DoubleType(), True, {'rounding': '0', 'from': 'New_Trade_PNL_Day_Ahead'}),
        StructField('New_Trade_Pnl_Within_Day', DoubleType(), True, {'rounding': '0', 'from': 'New_Trade_PNL_Within_Day'}),
        StructField('Impact_Of_Amendments', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Amendments'}),
        StructField('Impact_Of_Cancellations', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Cancellations'}),
        StructField('Impact_Of_Closeouts', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Closeouts'}),
        StructField('Impact_Of_Volume_Change', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Volume_Change'}),
        StructField('Impact_Of_Spot_FX', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Spot_FX'}),
        StructField('Impact_Of_Vega_Gamma', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Vega_Gamma'}),
        StructField('Impact_Of_Cross_Gamma', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Cross_Gamma'}),
        StructField('Impact_Of_Cross_Vega_Gamma', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Cross_Vega_Gamma'}),
        StructField('Impact_Of_Exercise_Option', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Exercise_Option'}),
        StructField('Impact_Of_Rho', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Rho'}),
        StructField('Impact_Of_Delta_Shape', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Delta_Shape'}),
        StructField('Shaped_Deal', StringType(), True, {}),
        StructField('Impact_Option_Expiry', DoubleType(), True, {'rounding': '0', 'from': 'impact_option_expiry'}),
        StructField('Impact_Of_Reset_TAC_Delta', DoubleType(), True, {'rounding': '0', 'from': 'impact_of_reset_tac_delta'}),
        StructField('Impact_Of_Delta_Pwr_Fut_Da', DoubleType(), True, {'rounding': '0', 'from': 'impact_of_delta_pwr_fut_da'}),
        StructField('Impact_Of_Df_Delta', DoubleType(), True, {'rounding': '0', 'from': 'impact_of_df_delta'}),
        StructField('Bench', StringType(), True, {}),
        StructField('Team', StringType(), True, {}),
        StructField('Strategy', StringType(), True, {}),
        StructField('Trader', StringType(), True, {}),
        StructField('Data_Status', StringType(), True, {}),
        StructField('Data_Status_Description', StringType(), True, {}),
        StructField('Refdata_Datetime', TimestampType(), True, {}),
        StructField('Run_Datetime', TimestampType(), True, {}),
])
