from pyspark.sql.types import StructField, StructType, StringType, DoubleType, IntegerType, DateType, TimestampType

typed_output_schema = StructType([
        StructField('Cumulative_Run_ID', IntegerType(), True, {}),
        StructField('Version', IntegerType(), True, {}),
        StructField('COB_Date', DateType(), True, {}),
        StructField('Valuation_Definition', StringType(), True, {}),
        StructField('Report_Type', StringType(), True, {}),
        StructField('Valuation_Key', StringType(), True, {}),
        StructField('Trade_Group_ID', IntegerType(), True, {}),
        StructField('Trade_ID', IntegerType(), True, {}),
        StructField('Trade_Settlement_Period_ID', IntegerType(), True, {}),
        StructField('Non_Trade_Valuation_Key', StringType(), True, {}),
        StructField('Book', StringType(), True, {}),
        StructField('Legal_Entity', StringType(), True, {}),
        StructField('Counterparty', StringType(), True, {}),
        StructField('Product_Type', StringType(), True, {}),
        StructField('Charge_Type', StringType(), True, {}),
        StructField('Cargo_Product', StringType(), True, {}),
        StructField('Leg_Type', StringType(), True, {}),
        StructField('Buy_Sell', StringType(), True, {}),
        StructField('Trade_Currency', StringType(), True, {}),
        StructField('Reporting_Currency', StringType(), True, {}),
        StructField('DTD_Total_Disc_Deal', DoubleType(), True, {}),
        StructField('DTD_Real_Disc_Deal', DoubleType(), True, {}),
        StructField('DTD_Unreal_Disc_Deal', DoubleType(), True, {}),
        StructField('DTD_Total_Undisc_Deal', DoubleType(), True, {}),
        StructField('DTD_Real_Undisc_Deal', DoubleType(), True, {}),
        StructField('DTD_Unreal_Undisc_Deal', DoubleType(), True, {}),
        StructField('DTD_Total_Disc_Pf', DoubleType(), True, {}),
        StructField('DTD_Real_Disc_Pf', DoubleType(), True, {}),
        StructField('DTD_Unreal_Disc_Pf', DoubleType(), True, {}),
        StructField('DTD_Total_Undisc_Pf', DoubleType(), True, {}),
        StructField('DTD_Real_Undisc_Pf', DoubleType(), True, {}),
        StructField('DTD_Unreal_Undisc_Pf', DoubleType(), True, {}),
        StructField('MTD_Total_Disc_Deal', DoubleType(), True, {}),
        StructField('MTD_Real_Disc_Deal', DoubleType(), True, {}),
        StructField('MTD_Unreal_Disc_Deal', DoubleType(), True, {}),
        StructField('MTD_Total_Undisc_Deal', DoubleType(), True, {}),
        StructField('MTD_Real_Undisc_Deal', DoubleType(), True, {}),
        StructField('MTD_Unreal_Undisc_Deal', DoubleType(), True, {}),
        StructField('MTD_Total_Disc_Pf', DoubleType(), True, {}),
        StructField('MTD_Real_Disc_Pf', DoubleType(), True, {}),
        StructField('MTD_Unreal_Disc_Pf', DoubleType(), True, {}),
        StructField('MTD_Total_Undisc_Pf', DoubleType(), True, {}),
        StructField('MTD_Real_Undisc_Pf', DoubleType(), True, {}),
        StructField('MTD_Unreal_Undisc_Pf', DoubleType(), True, {}),
        StructField('QTD_Total_Disc_Deal', DoubleType(), True, {}),
        StructField('QTD_Real_Disc_Deal', DoubleType(), True, {}),
        StructField('QTD_Unreal_Disc_Deal', DoubleType(), True, {}),
        StructField('QTD_Total_Undisc_Deal', DoubleType(), True, {}),
        StructField('QTD_Real_Undisc_Deal', DoubleType(), True, {}),
        StructField('QTD_Unreal_Undisc_Deal', DoubleType(), True, {}),
        StructField('QTD_Total_Disc_Pf', DoubleType(), True, {}),
        StructField('QTD_Real_Disc_Pf', DoubleType(), True, {}),
        StructField('QTD_Unreal_Disc_Pf', DoubleType(), True, {}),
        StructField('QTD_Total_Undisc_Pf', DoubleType(), True, {}),
        StructField('QTD_Real_Undisc_Pf', DoubleType(), True, {}),
        StructField('QTD_Unreal_Undisc_Pf', DoubleType(), True, {}),
        StructField('YTD_Total_Disc_Deal', DoubleType(), True, {}),
        StructField('YTD_Real_Disc_Deal', DoubleType(), True, {}),
        StructField('YTD_Unreal_Disc_Deal', DoubleType(), True, {}),
        StructField('YTD_Total_Undisc_Deal', DoubleType(), True, {}),
        StructField('YTD_Real_Undisc_Deal', DoubleType(), True, {}),
        StructField('YTD_Unreal_Undisc_Deal', DoubleType(), True, {}),
        StructField('YTD_Total_Disc_Pf', DoubleType(), True, {}),
        StructField('YTD_Real_Disc_Pf', DoubleType(), True, {}),
        StructField('YTD_Unreal_Disc_Pf', DoubleType(), True, {}),
        StructField('YTD_Total_Undisc_Pf', DoubleType(), True, {}),
        StructField('YTD_Real_Undisc_Pf', DoubleType(), True, {}),
        StructField('YTD_Unreal_Undisc_Pf', DoubleType(), True, {}),
        StructField('LTD_Total_Disc_Deal', DoubleType(), True, {}),
        StructField('LTD_Real_Disc_Deal', DoubleType(), True, {}),
        StructField('LTD_Unreal_Disc_Deal', DoubleType(), True, {}),
        StructField('LTD_Total_Undisc_Deal', DoubleType(), True, {}),
        StructField('LTD_Real_Undisc_Deal', DoubleType(), True, {}),
        StructField('LTD_Unreal_Undisc_Deal', DoubleType(), True, {}),
        StructField('LTD_Total_Disc_Pf', DoubleType(), True, {}),
        StructField('LTD_Real_Disc_Pf', DoubleType(), True, {}),
        StructField('LTD_Unreal_Disc_Pf', DoubleType(), True, {}),
        StructField('LTD_Total_Undisc_Pf', DoubleType(), True, {}),
        StructField('LTD_Real_Undisc_Pf', DoubleType(), True, {}),
        StructField('LTD_Unreal_Undisc_Pf', DoubleType(), True, {}),
        StructField('Run_Datetime', TimestampType(), True, {}),
])


transformed_output_schema = StructType([
        StructField('Valuation_Date', DateType(), True, {'from': 'COB_Date'}),
        StructField('Trade_ID', IntegerType(), True, {}),
        StructField('Trade_Group_ID', IntegerType(), True, {}),
        StructField('Portfolio', StringType(), True, {'from': 'Book'}),
        StructField('Product_Type', StringType(), True, {}),
        StructField('Cargo_Product', StringType(), True, {}),
        StructField('DTD_Total_Pf', DoubleType(), True, {'from': 'DTD_Total_Disc_Pf'}),
        StructField('DTD_Real_Pf', DoubleType(), True, {'from': 'DTD_Real_Disc_Pf'}),
        StructField('DTD_Unreal_Pf', DoubleType(), True, {'from': 'DTD_Unreal_Disc_Pf'}),
        StructField('DTD_Total_Undisc_Pf', DoubleType(), True, {'from': 'DTD_Total_Undisc_Pf'}),
        StructField('DTD_Real_Undisc_Pf', DoubleType(), True, {'from': 'DTD_Real_Undisc_Pf'}),
        StructField('DTD_Unreal_Undisc_Pf', DoubleType(), True, {'from': 'DTD_Unreal_Undisc_Pf'}),
        StructField('DTD_Total_Tran', DoubleType(), True, {'from': 'DTD_Total_Disc_Deal'}),
        StructField('DTD_Real_Tran', DoubleType(), True, {'from': 'DTD_Real_Disc_Deal'}),
        StructField('DTD_Unreal_Tran', DoubleType(), True, {'from': 'DTD_Unreal_Disc_Deal'}),
        StructField('DTD_Total_Undisc_Tran', DoubleType(), True, {'from': 'DTD_Total_Undisc_Deal'}),
        StructField('DTD_Real_Undisc_Tran', DoubleType(), True, {'from': 'DTD_Real_Undisc_Deal'}),
        StructField('DTD_Unreal_Undisc_Tran', DoubleType(), True, {'from': 'DTD_Unreal_Undisc_Deal'}),
        StructField('YTD_Total_Pf', DoubleType(), True, {'from': 'YTD_Total_Disc_Pf'}),
        StructField('YTD_Real_Pf', DoubleType(), True, {'from': 'YTD_Real_Disc_Pf'}),
        StructField('YTD_Unreal_Pf', DoubleType(), True, {'from': 'YTD_Unreal_Disc_Pf'}),
        StructField('YTD_Total_Undisc_Pf', DoubleType(), True, {}),
        StructField('YTD_Real_Undisc_Pf', DoubleType(), True, {}),
        StructField('YTD_Unreal_Undisc_Pf', DoubleType(), True, {}),
        StructField('YTD_Total_Tran', DoubleType(), True, {'from': 'YTD_Total_Disc_Deal'}),
        StructField('YTD_Real_Tran', DoubleType(), True, {'from': 'YTD_Real_Disc_Deal'}),
        StructField('YTD_Unreal_Tran', DoubleType(), True, {'from': 'YTD_Unreal_Disc_Deal'}),
        StructField('YTD_Total_Undisc_Tran', DoubleType(), True, {'from': 'YTD_Total_Undisc_Deal'}),
        StructField('YTD_Real_Undisc_Tran', DoubleType(), True, {'from': 'YTD_Real_Undisc_Deal'}),
        StructField('YTD_Unreal_Undisc_Tran', DoubleType(), True, {'from': 'YTD_Unreal_Undisc_Deal'}),
        StructField('LTD_Total_Pf', DoubleType(), True, {'from': 'LTD_Total_Disc_Pf'}),
        StructField('LTD_Real_Pf', DoubleType(), True, {'from': 'LTD_Real_Disc_Pf'}),
        StructField('LTD_Unreal_Pf', DoubleType(), True, {'from': 'LTD_Unreal_Disc_Pf'}),
        StructField('LTD_Total_Undisc_Pf', DoubleType(), True, {}),
        StructField('LTD_Real_Undisc_Pf', DoubleType(), True, {}),
        StructField('LTD_Unreal_Undisc_Pf', DoubleType(), True, {}),
        StructField('LTD_Total_Tran', DoubleType(), True, {'from': 'LTD_Total_Disc_Deal'}),
        StructField('LTD_Real_Tran', DoubleType(), True, {'from': 'LTD_Real_Disc_Deal'}),
        StructField('LTD_Unreal_Tran', DoubleType(), True, {'from': 'LTD_Unreal_Disc_Deal'}),
        StructField('LTD_Total_Undisc_Tran', DoubleType(), True, {'from': 'LTD_Total_Undisc_Deal'}),
        StructField('LTD_Real_Undisc_Tran', DoubleType(), True, {'from': 'LTD_Real_Undisc_Deal'}),
        StructField('LTD_Unreal_Undisc_Tran', DoubleType(), True, {'from': 'LTD_Unreal_Undisc_Deal'}),
        StructField('MTD_Total_Pf', DoubleType(), True, {'from': 'MTD_Total_Disc_Pf'}),
        StructField('MTD_Real_Pf', DoubleType(), True, {'from': 'MTD_Real_Disc_Pf'}),
        StructField('MTD_Unreal_Pf', DoubleType(), True, {'from': 'MTD_Unreal_Disc_Pf'}),
        StructField('MTD_Total_Undisc_Pf', DoubleType(), True, {}),
        StructField('MTD_Real_Undisc_Pf', DoubleType(), True, {}),
        StructField('MTD_Unreal_Undisc_Pf', DoubleType(), True, {}),
        StructField('MTD_Total_Tran', DoubleType(), True, {'from': 'MTD_Total_Disc_Deal'}),
        StructField('MTD_Real_Tran', DoubleType(), True, {'from': 'MTD_Real_Disc_Deal'}),
        StructField('MTD_Unreal_Tran', DoubleType(), True, {'from': 'MTD_Unreal_Disc_Deal'}),
        StructField('MTD_Total_Undisc_Tran', DoubleType(), True, {'from': 'MTD_Total_Undisc_Deal'}),
        StructField('MTD_Real_Undisc_Deal', DoubleType(), True, {'from': 'MTD_Real_Undisc_Deal'}),
        StructField('MTD_Unreal_Undisc_Deal', DoubleType(), True, {'from': 'MTD_Unreal_Undisc_Deal'}),
        StructField('QTD_Total_Pf', DoubleType(), True, {'from': 'QTD_Total_Disc_Pf'}),
        StructField('QTD_Real_Pf', DoubleType(), True, {'from': 'QTD_Real_Disc_Pf'}),
        StructField('QTD_Unreal_Pf', DoubleType(), True, {'from': 'QTD_Unreal_Disc_Pf'}),
        StructField('QTD_Total_Undisc_Pf', DoubleType(), True, {'from': 'QTD_Total_Undisc_Pf'}),
        StructField('QTD_Real_Undisc_Pf', DoubleType(), True, {'from': 'QTD_Real_Undisc_Pf'}),
        StructField('QTD_Unreal_Undisc_Pf', DoubleType(), True, {'from': 'QTD_Unreal_Undisc_Pf'}),
        StructField('QTD_Total_Tran', DoubleType(), True, {'from': 'QTD_Total_Disc_Deal'}),
        StructField('QTD_Real_Tran', DoubleType(), True, {'from': 'QTD_Real_Disc_Deal'}),
        StructField('QTD_Unreal_Tran', DoubleType(), True, {'from': 'QTD_Unreal_Disc_Deal'}),
        StructField('QTD_Total_Undisc_Tran', DoubleType(), True, {'from': 'QTD_Total_Undisc_Deal'}),
        StructField('QTD_Real_Undisc_Tran', DoubleType(), True, {'from': 'QTD_Real_Undisc_Deal'}),
        StructField('QTD_Unreal_Undisc_Tran', DoubleType(), True, {'from': 'QTD_Unreal_Undisc_Deal'}),
        StructField('Counterparty', StringType(), True, {}),
        StructField('Legal_Entity', StringType(), True, {}),
        StructField('Charge_Type', StringType(), True, {}),
        StructField('Leg_Type', StringType(), True, {}),
        StructField('Buy_Sell', StringType(), True, {}),
        StructField('Trade_Currency', StringType(), True, {}),
        StructField('Reporting_Currency', StringType(), True, {}),
        StructField('Trade_Settlement_Period_ID', IntegerType(), True, {}),
        StructField('Bench', StringType(), True, {}),
        StructField('Team', StringType(), True, {}),
        StructField('Strategy', StringType(), True, {}),
        StructField('Trader', StringType(), True, {}),
        StructField('Data_Status', StringType(), True, {}),
        StructField('Data_Status_Description', StringType(), True, {}),
        StructField('Refdata_Datetime', TimestampType(), True, {}),
        StructField('Run_Datetime', TimestampType(), True, {}),
])
