from pyspark.sql.types import StructField, StructType, StringType, DateType, TimestampType

typed_output_schema = StructType([
        StructField('Run_Datetime', TimestampType(), True, {}),
        StructField('Toolset', StringType(), True, {}),
        StructField('Instrument_Type', StringType(), True, {}),
        StructField('Deal_Number', StringType(), True, {}),
        StructField('Offset_Deal_Number', StringType(), True, {}),
        StructField('Reference', StringType(), True, {}),
        StructField('Ticker', StringType(), True, {}),
        StructField('Transaction_Status', StringType(), True, {}),
        StructField('Template', StringType(), True, {}),
        StructField('Input_Date', TimestampType(), True, {'tst_format': 'dd/MM/yyyy hh:mm:ss aa'}),
        StructField('Trade_Date', DateType(), True, {'dt_format': 'dd-MMM-yyyy'}),
        StructField('Start_Date', DateType(), True, {'dt_format': 'dd-MMM-yyyy'}),
        StructField('Maturity_Date', DateType(), True, {'dt_format': 'dd-MMM-yyyy'}),
        StructField('Internal_Business_Unit', StringType(), True, {}),
        StructField('Internal_Legal_Entity', StringType(), True, {}),
        StructField('Internal_Portfolio', StringType(), True, {}),
        StructField('Trader', StringType(), True, {}),
        StructField('External_Business_Unit', StringType(), True, {}),
        StructField('External_Contact', StringType(), True, {}),
        StructField('External_Legal_Entity', StringType(), True, {}),
        StructField('External_Portfolio', StringType(), True, {}),
        StructField('Buy_Sell', StringType(), True, {}),
        StructField('Reval_Date', DateType(), True, {'dt_format': 'dd-MMM-yyyy'}),
])


transformed_output_schema = StructType([
        StructField('Valuation_Date', DateType(), True, {}),
        StructField('Deal_Number', StringType(), True, {}),
        StructField('Instrument_Type', StringType(), True, {}),
        StructField('Portfolio', StringType(), True, {'from': 'Internal_Portfolio'}),
        StructField('External_Portfolio', StringType(), True, {}),
        StructField('Internal_Business_Unit', StringType(), True, {}),
        StructField('Internal_Legal_Entity', StringType(), True, {}),
        StructField('External_Business_Unit', StringType(), True, {}),
        StructField('External_Legal_Entity', StringType(), True, {}),
        StructField('Reference', StringType(), True, {}),
        StructField('Toolset', StringType(), True, {}),
        StructField('External_Contact', StringType(), True, {}),
        StructField('Trade_Date', DateType(), True, {}),
        StructField('Buy_Sell', StringType(), True, {}),
        StructField('Transaction_Status', StringType(), True, {}),
        StructField('Trader', StringType(), True, {}),
        StructField('Offset_Deal_Number', StringType(), True, {}),
        StructField('Ticker', StringType(), True, {}),
        StructField('Template', StringType(), True, {}),
        StructField('Input_Date', TimestampType(), True, {}),
        StructField('Start_Date', DateType(), True, {}),
        StructField('Maturity_Date', DateType(), True, {}),
        StructField('Legal_Entity_Name', StringType(), True, {'from': 'Internal_Business_Unit'}),
        StructField('Counterparty_Name', StringType(), True, {'from': 'External_Business_Unit'}),
        StructField('Data_Status', StringType(), True, {}),
        StructField('Data_Status_Description', StringType(), True, {}),
        StructField('Refdata_Datetime', TimestampType(), True, {}),
        StructField('Run_Datetime', TimestampType(), True, {}),
])
