from pyspark.sql.types import StructField, StructType, StringType, DoubleType, DateType, TimestampType

typed_output_schema = StructType([
    StructField('Run_Datetime', TimestampType(), True),
    StructField('Reval_Date', DateType(), True),
    StructField('Portfolio', StringType(), True),
    StructField('Portfolio_CCY', StringType(), True),
    StructField('DtD_PF_CCY', DoubleType(), True),
    StructField('DtD_Adj_PF_CCY', DoubleType(), True),
    StructField('DtD_PF_CCY_and_Adj', DoubleType(), True),
    StructField('MtD_PF_CCY', DoubleType(), True),
    StructField('MtD_Adj_PF_CCY', DoubleType(), True),
    StructField('MtD_PF_CCY_and_Adj', DoubleType(), True),
    StructField('YtD_PF_CCY', DoubleType(), True),
    StructField('YtD_Adj_PF_CCY', DoubleType(), True),
    StructField('YtD_PF_CCY_and_Adj', DoubleType(), True),
    StructField('DtD_USD', DoubleType(), True),
    StructField('DtD_Adj_USD', DoubleType(), True),
    StructField('DtD_USD_and_Adj', DoubleType(), True),
    StructField('MtD_USD', DoubleType(), True),
    StructField('MtD_Adj_USD', DoubleType(), True),
    StructField('MtD_USD_and_Adj', DoubleType(), True),
    StructField('YtD_USD', DoubleType(), True),
    StructField('YtD_Adj_USD', DoubleType(), True),
    StructField('YtD_USD_and_Adj', DoubleType(), True),
])


transformed_output_schema = StructType([
        StructField('Valuation_Date', DateType(), True, {'from': 'Reval_Date'}),
        StructField('Portfolio', StringType(), True, {}),
        StructField('DTD_Total_Pf', DoubleType(), True, {'from': 'DtD_PF_CCY'}),
        StructField('DTD_Adj_Pf', DoubleType(), True, {'from': 'DtD_Adj_PF_CCY'}),
        StructField('DTD_Total_And_Adj_Pf', DoubleType(), True, {'from': 'DtD_PF_CCY_and_Adj'}),
        StructField('MTD_Total_Pf', DoubleType(), True, {'from': 'MtD_PF_CCY'}),
        StructField('MTD_Adj_Pf', DoubleType(), True, {'from': 'MtD_Adj_PF_CCY'}),
        StructField('MTD_Total_And_Adj_Pf', DoubleType(), True, {'from': 'MtD_PF_CCY_and_Adj'}),
        StructField('YTD_Total_Pf', DoubleType(), True, {'from': 'YtD_PF_CCY'}),
        StructField('YTD_Adj_Pf', DoubleType(), True, {'from': 'YtD_Adj_PF_CCY'}),
        StructField('YTD_Total_And_Adj_Pf', DoubleType(), True, {'from': 'YtD_PF_CCY_and_Adj'}),
        StructField('DTD_Total_USD', DoubleType(), True, {'from': 'DtD_USD'}),
        StructField('DTD_Adj_USD', DoubleType(), True, {'from': 'DtD_Adj_USD'}),
        StructField('DTD_Total_And_Adj_USD', DoubleType(), True, {'from': 'DtD_USD_and_Adj'}),
        StructField('MTD_Total_USD', DoubleType(), True, {'from': 'MtD_USD'}),
        StructField('MTD_Adj_USD', DoubleType(), True, {'from': 'MtD_Adj_USD'}),
        StructField('MTD_Total_And_Adj_USD', DoubleType(), True, {'from': 'MtD_USD_and_Adj'}),
        StructField('YTD_Total_USD', DoubleType(), True, {'from': 'YtD_USD'}),
        StructField('YTD_Adj_USD', DoubleType(), True, {'from': 'YtD_Adj_USD'}),
        StructField('YTD_Total_And_Adj_USD', DoubleType(), True, {'from': 'YtD_USD_and_Adj'}),
        StructField('Portfolio_Currency', StringType(), True, {'from': 'Portfolio_CCY'}),
        StructField('Bench', StringType(), True, {}),
        StructField('Team', StringType(), True, {}),
        StructField('Strategy', StringType(), True, {}),
        StructField('Trader', StringType(), True, {}),
        StructField('Data_Status', StringType(), True, {}),
        StructField('Data_Status_Description', StringType(), True, {}),
        StructField('Refdata_Datetime', TimestampType(), True, {}),
        StructField('Run_Datetime', TimestampType(), True, {}),
])
