from pyspark.sql.types import StructField, StructType, StringType, DoubleType, IntegerType, DateType, TimestampType

typed_output_schema = StructType([
        StructField('Run_Datetime', TimestampType(), True, {}),
        StructField('Reval_Date', DateType(), True, {}),
        StructField('Portfolio', StringType(), True, {}),
        StructField('Action', StringType(), True, {}),
        StructField('Deal_Number', IntegerType(), True, {}),
        StructField('Tran_No', IntegerType(), True, {}),
        StructField('Ins_No', IntegerType(), True, {}),
        StructField('Instrument_Type', StringType(), True, {}),
        StructField('Trader', StringType(), True, {}),
        StructField('Internal_Legal_Entity', StringType(), True, {}),
        StructField('Internal_Business_Unit', StringType(), True, {}),
        StructField('External_Business_Unit', StringType(), True, {}),
        StructField('Master_Agreement', StringType(), True, {}),
        StructField('Ticker', StringType(), True, {}),
        StructField('Trade_Date', DateType(), True, {}),
        StructField('Start_Date', DateType(), True, {}),
        StructField('End_Date', DateType(), True, {}),
        StructField('Buy_Sell', StringType(), True, {}),
        StructField('Pipeline', StringType(), True, {}),
        StructField('Delivery_Location', StringType(), True, {}),
        StructField('Pricing_Template', StringType(), True, {}),
        StructField('Index', StringType(), True, {}),
        StructField('Price', DoubleType(), True, {}),
        StructField('Price_Unit', StringType(), True, {}),
        StructField('Currency', StringType(), True, {}),
        StructField('Volume', IntegerType(), True, {}),
        StructField('Volume_Unit', StringType(), True, {}),
        StructField('Volume_Type', StringType(), True, {}),
        StructField('Total_Volume', StringType(), True, {}),
        StructField('Execution_Broker', StringType(), True, {}),
        StructField('Execution_Brokerage', DoubleType(), True, {}),
        StructField('Clearing_Broker', StringType(), True, {}),
        StructField('Clearing_Brokerage', DoubleType(), True, {}),
        StructField('Deal_Premium', StringType(), True, {}),
        StructField('Portfolio_Currency', StringType(), True, {}),
        StructField('PnL_Portfolio_Ccy', DoubleType(), True, {}),
        StructField('Amender', StringType(), True, {}),
        StructField('Last_Update_Date', TimestampType(), True, {}),
        StructField('Status', StringType(), True, {}),
        StructField('LNG_Cargo_ID', StringType(), True, {}),
        StructField('LNG_Cargo_ID_Offset', StringType(), True, {}),
        StructField('Amendment_Reason', StringType(), True, {}),
        StructField('Deal_Comments', StringType(), True, {}),
])


transformed_output_schema = StructType([
        StructField('Valuation_Date', DateType(), True, {'from': 'Reval_Date'}),
        StructField('Portfolio', StringType(), True, {'from': 'Portfolio'}),
        StructField('Action', StringType(), True, {'from': 'Action'}),
        StructField('Deal_Number', IntegerType(), True, {'from': 'Deal_Number'}),
        StructField('Tran_Num', IntegerType(), True, {'from': 'Tran_No'}),
        StructField('Instrument_Type', StringType(), True, {'from': 'Instrument_Type'}),
        StructField('Internal_Legal_Entity', StringType(), True, {'from': 'Internal_Legal_Entity'}),
        StructField('Internal_Business_Unit', StringType(), True, {'from': 'Internal_Business_Unit'}),
        StructField('External_Business_Unit', StringType(), True, {'from': 'External_Business_Unit'}),
        StructField('Master_Agreement', StringType(), True, {'from': 'Master_Agreement'}),
        StructField('Ticker', StringType(), True, {'from': 'Ticker'}),
        StructField('Trade_Date', DateType(), True, {}),
        StructField('Start_Date', DateType(), True, {}),
        StructField('End_Date', DateType(), True, {}),
        StructField('Buy_Sell', StringType(), True, {'from': 'Buy_Sell'}),
        StructField('Pipeline', StringType(), True, {'from': 'Pipeline'}),
        StructField('Delivery_Location', StringType(), True, {'from': 'Delivery_Location'}),
        StructField('Pricing_Template', StringType(), True, {'from': 'Pricing_Template'}),
        StructField('Index', StringType(), True, {'from': 'Index'}),
        StructField('Price', DoubleType(), True, {'from': 'Price'}),
        StructField('Price_Unit', StringType(), True, {'from': 'Price_Unit'}),
        StructField('Currency', StringType(), True, {'from': 'Currency'}),
        StructField('Volume', IntegerType(), True, {'from': 'Volume'}),
        StructField('Volume_Unit', StringType(), True, {'from': 'Volume_Unit'}),
        StructField('Volume_Type', StringType(), True, {'from': 'Volume_Type'}),
        StructField('Total_Volume', StringType(), True, {'from': 'Total_Volume'}),
        StructField('Execution_Broker', StringType(), True, {'from': 'Execution_Broker'}),
        StructField('Execution_Brokerage', DoubleType(), True, {'from': 'Execution_Brokerage'}),
        StructField('Clearing_Broker', StringType(), True, {'from': 'Clearing_Broker'}),
        StructField('Clearing_Brokerage', DoubleType(), True, {'from': 'Clearing_Brokerage'}),
        StructField('Deal_Premium', StringType(), True, {'from': 'Deal_Premium'}),
        StructField('Portfolio_Currency', StringType(), True, {'from': 'Portfolio_Currency'}),
        StructField('LTD_Total_Pf', DoubleType(), True, {'from': 'PnL_Portfolio_Ccy'}),
        StructField('Amender', StringType(), True, {'from': 'Amender'}),
        StructField('Last_Update_Date', TimestampType(), True, {}),
        StructField('Status', StringType(), True, {'from': 'Status'}),
        StructField('LNG_Cargo_ID', StringType(), True, {'from': 'LNG_Cargo_ID'}),
        StructField('LNG_Cargo_ID_Offset', StringType(), True, {'from': 'LNG_Cargo_ID_Offset'}),
        StructField('Amendment_Reason', StringType(), True, {'from': 'Amendment_Reason'}),
        StructField('Deal_Comments', StringType(), True, {'from': 'Deal_Comments'}),
        StructField('Counterparty', StringType(), True, {}),
        StructField('Legal_Entity', StringType(), True, {}),
        StructField('Bench', StringType(), True, {}),
        StructField('Team', StringType(), True, {}),
        StructField('Strategy', StringType(), True, {}),
        StructField('Trader', StringType(), True, {}),
        StructField('Data_Status', StringType(), True, {}),
        StructField('Run_Datetime', TimestampType(), True, {'from': 'Run_Datetime'}),
        StructField('Data_Status_Description', StringType(), True, {}),
        StructField('Refdata_Datetime', TimestampType(), True, {}),
])
