from pyspark.sql.types import StructField, StructType, StringType, DoubleType, IntegerType, DateType, TimestampType

typed_output_schema = StructType([
        StructField('Run_Datetime', TimestampType(), True, {}),
        StructField('Reval_Date', DateType(), True, {}),
        StructField('Portfolio', StringType(), True, {}),
        StructField('Curve_Name', StringType(), True, {}),
        StructField('Coverage_Start_Date', DateType(), True, {}),
        StructField('Coverage_End_Date', DateType(), True, {}),
        StructField('Delta_By_Volume', DoubleType(), True, {}),
        StructField('Price_Yesterday', DoubleType(), True, {}),
        StructField('Price_Today', DoubleType(), True, {}),
        StructField('Impact_of_Delta', DoubleType(), True, {}),
        StructField('Impact_of_Gamma', DoubleType(), True, {}),
        StructField('Scenario_Impact_of_Delta', DoubleType(), True, {}),
        StructField('Scenario_Impact_of_Gamma', DoubleType(), True, {}),
        StructField('USD_Impact_of_Delta', DoubleType(), True, {}),
        StructField('USD_Impact_of_Gamma', DoubleType(), True, {}),
        StructField('Delta_Yesterday', DoubleType(), True, {}),
        StructField('Gamma_Yesterday', DoubleType(), True, {}),
        StructField('Grid_Point', StringType(), True, {}),
        StructField('Gridpoint_End_Date', DateType(), True, {}),
        StructField('Gridpoint_ID', IntegerType(), True, {}),
        StructField('Impact_of_Delta_Shape', DoubleType(), True, {}),
        StructField('USD_Impact_of_Delta_Shape', DoubleType(), True, {}),
        StructField('Scenario_Impact_of_Delta_Shape', DoubleType(), True, {}),
        StructField('Shaped_Deal', StringType(), True, {}),
])


transformed_output_schema = StructType([
        StructField('Valuation_Date', DateType(), True, {'from': 'Reval_Date'}),
        StructField('Portfolio', StringType(), True, {}),
        StructField('Projection_Index', StringType(), True, {'from': 'Curve_Name'}),
        StructField('Coverage_Start_Date', DateType(), True, {}),
        StructField('Coverage_End_Date', DateType(), True, {}),
        StructField('Delta_By_Volume', DoubleType(), True, {'rounding': '0'}),
        StructField('Price_Yesterday', DoubleType(), True, {}),
        StructField('Price_Today', DoubleType(), True, {}),
        StructField('Impact_Of_Delta', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Delta'}),
        StructField('Impact_Of_Gamma', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Gamma'}),
        StructField('Scenario_Impact_Of_Delta', DoubleType(), True, {'rounding': '0', 'from': 'Scenario_Impact_of_Delta'}),
        StructField('Scenario_Impact_Of_Gamma', DoubleType(), True, {'rounding': '0', 'from': 'Scenario_Impact_of_Gamma'}),
        StructField('USD_Impact_Of_Delta', DoubleType(), True, {'rounding': '0', 'from': 'USD_Impact_of_Delta'}),
        StructField('USD_Impact_Of_Gamma', DoubleType(), True, {'rounding': '0', 'from': 'USD_Impact_of_Gamma'}),
        StructField('Delta_Yesterday', DoubleType(), True, {'rounding': '0'}),
        StructField('Gamma_Yesterday', DoubleType(), True, {'rounding': '0'}),
        StructField('Grid_Point', StringType(), True, {}),
        StructField('Gridpoint_End_Date', DateType(), True, {}),
        StructField('Gridpoint_ID', IntegerType(), True, {}),
        StructField('Impact_Of_Delta_Shape', DoubleType(), True, {'rounding': '0', 'from': 'Impact_of_Delta_Shape'}),
        StructField('USD_Impact_Of_Delta_Shape', DoubleType(), True, {'rounding': '0', 'from': 'USD_Impact_of_Delta_Shape'}),
        StructField('Scenario_Impact_Of_Delta_Shape', DoubleType(), True, {'rounding': '0', 'from': 'Scenario_Impact_of_Delta_Shape'}),
        StructField('Shaped_Deal', StringType(), True, {}),
        StructField('Bench', StringType(), True, {}),
        StructField('Team', StringType(), True, {}),
        StructField('Strategy', StringType(), True, {}),
        StructField('Trader', StringType(), True, {}),
        StructField('Data_Status', StringType(), True, {}),
        StructField('Data_Status_Description', StringType(), True, {}),
        StructField('Refdata_Datetime', TimestampType(), True, {}),
        StructField('Run_Datetime', TimestampType(), True, {}),
])
