from pyspark.sql.types import StructField, StructType, StringType, DoubleType, \
                                IntegerType, DateType, TimestampType, BooleanType

typed_output_schema = StructType([
        StructField('Valuation_Definition_Name', StringType(), True, {}),
        StructField('Current_Valuation_Run_ID', IntegerType(), True, {}),
        StructField('Previous_Valuation_Run_ID', IntegerType(), True, {}),
        StructField('Current_COB_Date', DateType(), True, {}),
        StructField('Previous_COB_Date', DateType(), True, {}),
        StructField('Delta_Sub_Type', StringType(), True, {}),
        StructField('Legal_Entity', StringType(), True, {}),
        StructField('Counterparty', StringType(), True, {}),
        StructField('Book', StringType(), True, {}),
        StructField('Strategy', StringType(), True, {}),
        StructField('Cargo_Reference', StringType(), True, {}),
        StructField('Chain', StringType(), True, {}),
        StructField('Product_Type', StringType(), True, {}),
        StructField('Charge_Type', StringType(), True, {}),
        StructField('Product', StringType(), True, {}),
        StructField('PNL_Start_Year', StringType(), True, {}),
        StructField('Book_Transfer', BooleanType(), True, {}),
        StructField('Trade_Group_ID', StringType(), True, {}),
        StructField('Trade_ID', StringType(), True, {}),
        StructField('Natural_Key', StringType(), True, {}),
        StructField('Valuation_Key', StringType(), True, {}),
        StructField('Trade_Status', StringType(), True, {}),
        StructField('Leg_Type', StringType(), True, {}),
        StructField('Settlement_Period_Start', DateType(), True, {}),
        StructField('Settlement_Period_End', DateType(), True, {}),
        StructField('Trade_Settlement_Period_ID', StringType(), True, {}),
        StructField('Delivery_Location', StringType(), True, {}),
        StructField('Trade_Date', DateType(), True, {}),
        StructField('Trader_NTID', StringType(), True, {}),
        StructField('Delivery_Start_Date', DateType(), True, {}),
        StructField('Delivery_End_Date', DateType(), True, {}),
        StructField('Buy_Sell', StringType(), True, {}),
        StructField('Trade_Currency', StringType(), True, {}),
        StructField('Delta_Unit_Type', StringType(), True, {}),
        StructField('Reporting_Tag', StringType(), True, {}),
        StructField('Commodity_Group', StringType(), True, {}),
        StructField('Reporting_Group', StringType(), True, {}),
        StructField('Index_Name', StringType(), True, {}),
        StructField('Curve_Name', StringType(), True, {}),
        StructField('Pricing_Maturity_Start', DateType(), True, {}),
        StructField('Pricing_Maturity_End', DateType(), True, {}),
        StructField('Pricing_Maturity_Period', StringType(), True, {}),
        StructField('Point_Month', StringType(), True, {}),
        StructField('Point_Date', DateType(), True, {}),
        StructField('Fixed_Float_Point', StringType(), True, {}),
        StructField('Forward_Point', IntegerType(), True, {}),
        StructField('Historic_Point', IntegerType(), True, {}),
        StructField('Settled_Point', IntegerType(), True, {}),
        StructField('Price_UOM', StringType(), True, {}),
        StructField('Price', DoubleType(), True, {}),
        StructField('Curve_Delta_UOM', StringType(), True, {}),
        StructField('Curve_Delta', DoubleType(), True, {}),
        StructField('Index_Price_UOM', StringType(), True, {}),
        StructField('Index_Price_Commodity_UOM', StringType(), True, {}),
        StructField('FX_Trade_Currency', StringType(), True, {}),
        StructField('FX_Reporting_Currency', StringType(), True, {}),
        StructField('FX_Rate_Spot', DoubleType(), True, {}),
        StructField('FX_Rate_Forward', DoubleType(), True, {}),
        StructField('DCF_Trade_Currency', DoubleType(), True, {}),
        StructField('DCF_Report_Currency', DoubleType(), True, {}),
        StructField('Year_Fraction', DoubleType(), True, {}),
        StructField('Payment_Month', StringType(), True, {}),
        StructField('Payment_Date', DateType(), True, {}),
        StructField('FX_Fixed_Float', StringType(), True, {}),
        StructField('FX_Delta', DoubleType(), True, {}),
        StructField('TradeReference', StringType(), True, {}),
        StructField('Curve_DCF_Report_Currency', StringType(), True, {}),
        StructField('RunDateTime', TimestampType(), True, {}),
])


transformed_output_schema = StructType([
        StructField('Source', StringType(), True, {}),
        StructField('Valuation_Date', DateType(), True, {'from': 'Current_COB_Date'}),
        StructField('Portfolio/Book', StringType(), True, {'from': 'Book'}),
        StructField('Projection_Index', StringType(), True, {'from': 'Curve_Name'}),
        StructField('Risk_Factor_Name', StringType(), True, {}),
        StructField('Limits_Group', StringType(), True, {}),
        StructField('MR_Delta', DoubleType(), True, {}),
        StructField('MR_Delta_UOM', StringType(), True, {'from': 'Curve_Delta_UOM'}),
        StructField('MR_Delta_Conformed', DoubleType(), True, {}),
        StructField('MR_Delta_Conformed_UOM', StringType(), True, {'from': 'Curve_Delta_UOM'}),
        StructField('MR_Delta_Therms', DoubleType(), True, {}),
        StructField('MR_Delta_MWh', DoubleType(), True, {}),
        StructField('MR_Delta_MMBtu', DoubleType(), True, {}),
        StructField('MR_Delta_BBL', DoubleType(), True, {}),
        StructField('MR_Delta_EUR', DoubleType(), True, {}),
        StructField('MR_Delta_GBP', DoubleType(), True, {}),
        StructField('MR_Gamma', DoubleType(), True, {}),
        StructField('MR_Vega', DoubleType(), True, {}),
        StructField('MR_Theta', DoubleType(), True, {}),
        StructField('Market_Value', DoubleType(), True, {}),
        StructField('Conversion_Rate', DoubleType(), True, {}),
        StructField('Bucket_Start_Date', DateType(), True, {'from': 'Pricing_Maturity_Start'}),
        StructField('Bucket_End_Date', DateType(), True, {'from': 'Pricing_Maturity_End'}),
        StructField('Bucket_Month', StringType(), True, {}),
        StructField('Bucket_Quarter', StringType(), True, {}),
        StructField('Bucket_Season', StringType(), True, {}),
        StructField('Bucket_Year', StringType(), True, {}),
        StructField('Bucket_Name', StringType(), True, {}),
        StructField('Bucket_Id', IntegerType(), True, {}),
        StructField('Bucket_Order', IntegerType(), True, {}),
        StructField('Grid_Point_ID', IntegerType(), True, {}),
        StructField('Grid_Point_Name', StringType(), True, {}),
        StructField('Grid_Point_Start_Date', DateType(), True, {}),
        StructField('Grid_Point_End_Date', DateType(), True, {}),
        StructField('Grid_Point_Month', DateType(), True, {}),
        StructField('Counterparty', StringType(), True, {}),
        StructField('Legal_Entity_Name', StringType(), True, {'from': 'Legal_Entity'}),
        StructField('Internal_BU', StringType(), True, {}),
        StructField('External_BU', StringType(), True, {}),
        StructField('External_Portfolio', StringType(), True, {}),
        StructField('Price', DoubleType(), True, {}),
        StructField('Price_UOM', StringType(), True, {}),
        StructField('Trade_Status', StringType(), True, {}),
        StructField('Trade_Date', DateType(), True, {}),
        StructField('Deal_Number', StringType(), True, {'from': 'Trade_ID'}),
        StructField('Deal_Trader', StringType(), True, {}),
        StructField('Instrument_Type', StringType(), True, {}),
        StructField('Expo_Type', StringType(), True, {}),
        StructField('Product_Type', StringType(), True, {}),
        StructField('Delta_Unit_Type', StringType(), True, {}),
        StructField('Cargo_Delivery_Month', IntegerType(), True, {}),
        StructField('Cargo_Delivery_Year', IntegerType(), True, {}),
        StructField('Cargo_Delivery_Location', StringType(), True, {'from': 'Delivery_Location'}),
        StructField('Cargo_Reference', StringType(), True, {}),
        StructField('Titan_Strategy', StringType(), True, {'from': 'Strategy'}),
        StructField('Liquid_Window', StringType(), True, {}),
        StructField('Bench', StringType(), True, {}),
        StructField('Team', StringType(), True, {}),
        StructField('Strategy', StringType(), True, {}),
        StructField('Trader', StringType(), True, {}),
        StructField('Data_Status', StringType(), True, {}),
        StructField('Data_Status_Description', StringType(), True, {}),
        StructField('RefData_Datetime', TimestampType(), True, {}),
        StructField('Run_Datetime', TimestampType(), True, {'from': 'RunDateTime'}),
])


combined_output_schema = StructType([
        StructField('Source', StringType(), True, {}),
        StructField('Valuation_Date', DateType(), True, {}),
        StructField('Portfolio/Book', StringType(), True, {}),
        StructField('Projection_Index', StringType(), True, {}),
        StructField('Risk_Factor_Name', StringType(), True, {}),
        StructField('Limits_Group', StringType(), True, {}),
        StructField('MR_Delta', DoubleType(), True, {}),
        StructField('MR_Delta_UOM', StringType(), True, {}),
        StructField('MR_Delta_Conformed', DoubleType(), True, {}),
        StructField('MR_Delta_Conformed_UOM', StringType(), True, {}),
        StructField('MR_Delta_Therms', DoubleType(), True, {}),
        StructField('MR_Delta_MWh', DoubleType(), True, {}),
        StructField('MR_Delta_MMBtu', DoubleType(), True, {}),
        StructField('MR_Delta_BBL', DoubleType(), True, {}),
        StructField('MR_Delta_EUR', DoubleType(), True, {}),
        StructField('MR_Delta_GBP', DoubleType(), True, {}),
        StructField('MR_Gamma', DoubleType(), True, {}),
        StructField('MR_Vega', DoubleType(), True, {}),
        StructField('MR_Theta', DoubleType(), True, {}),
        StructField('Market_Value', DoubleType(), True, {}),
        StructField('Conversion_Rate', DoubleType(), True, {}),
        StructField('Bucket_Start_Date', DateType(), True, {}),
        StructField('Bucket_End_Date', DateType(), True, {}),
        StructField('Bucket_Month', StringType(), True, {}),
        StructField('Bucket_Quarter', StringType(), True, {}),
        StructField('Bucket_Season', StringType(), True, {}),
        StructField('Bucket_Year', StringType(), True, {}),
        StructField('Bucket_Name', StringType(), True, {}),
        StructField('Bucket_Id', IntegerType(), True, {}),
        StructField('Bucket_Order', IntegerType(), True, {}),
        StructField('Grid_Point_ID', IntegerType(), True, {}),
        StructField('Grid_Point_Name', StringType(), True, {}),
        StructField('Grid_Point_Start_Date', DateType(), True, {}),
        StructField('Grid_Point_End_Date', DateType(), True, {}),
        StructField('Grid_Point_Month', DateType(), True, {}),
        StructField('Counterparty', StringType(), True, {}),
        StructField('Legal_Entity_Name', StringType(), True, {}),
        StructField('Internal_BU', StringType(), True, {}),
        StructField('External_Portfolio', StringType(), True, {}),
        StructField('Price', DoubleType(), True, {}),
        StructField('Price_UOM', StringType(), True, {}),
        StructField('Trade_Status', StringType(), True, {}),
        StructField('Trade_Date', DateType(), True, {}),
        StructField('Deal_Number', StringType(), True, {}),
        StructField('Instrument_Type', StringType(), True, {}),
        StructField('Expo_Type', StringType(), True, {}),
        StructField('Product_Type', StringType(), True, {}),
        StructField('Delta_Unit_Type', StringType(), True, {}),
        StructField('Cargo_Delivery_Month', IntegerType(), True, {}),
        StructField('Cargo_Delivery_Year', IntegerType(), True, {}),
        StructField('Cargo_Delivery_Location', StringType(), True, {}),
        StructField('Cargo_Reference', StringType(), True, {}),
        StructField('Titan_Strategy', StringType(), True, {}),
        StructField('Liquid_Window', StringType(), True, {}),
        StructField('Bench', StringType(), True, {}),
        StructField('Team', StringType(), True, {}),
        StructField('Strategy', StringType(), True, {}),
        StructField('Trader', StringType(), True, {}),
        StructField('Data_Status', StringType(), True, {}),
        StructField('Data_Status_Description', StringType(), True, {}),
        StructField('RefData_Datetime', TimestampType(), True, {}),
        StructField('Run_Datetime', TimestampType(), True, {}),
])
