from pyspark.sql.types import StructField, StructType, StringType, DoubleType, IntegerType, DateType, TimestampType


combined_output_schema = StructType([
        StructField('Source', StringType(), True, {}),
        StructField('Valuation_Date', DateType(), True, {}),
        StructField('Portfolio/Book', StringType(), True, {}),
        StructField('Projection_Index', StringType(), True, {}),
        StructField('Risk_Factor_Name', StringType(), True, {}),
        StructField('Limits_Group', StringType(), True, {}),
        StructField('MR_Delta', DoubleType(), True, {'rounding': '0'}),
        StructField('MR_Delta_UOM', StringType(), True, {}),
        StructField('MR_Delta_Conformed', DoubleType(), True, {'rounding': '0'}),
        StructField('MR_Delta_Conformed_UOM', StringType(), True, {}),
        StructField('MR_Delta_Therms', DoubleType(), True, {'rounding': '0'}),
        StructField('MR_Delta_MWh', DoubleType(), True, {'rounding': '0'}),
        StructField('MR_Delta_MMBtu', DoubleType(), True, {'rounding': '0'}),
        StructField('MR_Delta_BBL', DoubleType(), True, {'rounding': '0'}),
        StructField('MR_Delta_EUR', DoubleType(), True, {'rounding': '0'}),
        StructField('MR_Delta_GBP', DoubleType(), True, {'rounding': '0'}),
        StructField('MR_Gamma', DoubleType(), True, {'rounding': '0'}),
        StructField('MR_Vega', DoubleType(), True, {'rounding': '0'}),
        StructField('MR_Theta', DoubleType(), True, {'rounding': '0'}),
        StructField('Market_Value', DoubleType(), True, {'rounding': '0'}),
        StructField('Conversion_Rate', DoubleType(), True, {}),
        StructField('Bucket_Start_Date', DateType(), True, {}),
        StructField('Bucket_End_Date', DateType(), True, {}),
        StructField('Bucket_Month', StringType(), True, {}),
        StructField('Bucket_Quarter', StringType(), True, {}),
        StructField('Bucket_Season', StringType(), True, {}),
        StructField('Bucket_Year', StringType(), True, {}),
        StructField('Bucket_Name', StringType(), True, {}),
        StructField('Bucket_Id', IntegerType(), True, {}),
        StructField('Bucket_Order', IntegerType(), True, {}),
        StructField('Grid_Point_ID', IntegerType(), True, {}),
        StructField('Grid_Point_Name', StringType(), True, {}),
        StructField('Grid_Point_Start_Date', DateType(), True, {}),
        StructField('Grid_Point_End_Date', DateType(), True, {}),
        StructField('Grid_Point_Month', DateType(), True, {}),
        StructField('Counterparty', StringType(), True, {}),
        StructField('Legal_Entity_Name', StringType(), True, {}),
        StructField('Internal_BU', StringType(), True, {}),
        StructField('External_Portfolio', StringType(), True, {}),
        StructField('Price', DoubleType(), True, {}),
        StructField('Price_UOM', StringType(), True, {}),
        StructField('Trade_Status', StringType(), True, {}),
        StructField('Trade_Date', DateType(), True, {}),
        StructField('Deal_Number', StringType(), True, {}),
        StructField('Instrument_Type', StringType(), True, {}),
        StructField('Expo_Type', StringType(), True, {}),
        StructField('Product_Type', StringType(), True, {}),
        StructField('Delta_Unit_Type', StringType(), True, {}),
        StructField('Cargo_Delivery_Month', IntegerType(), True, {}),
        StructField('Cargo_Delivery_Year', IntegerType(), True, {}),
        StructField('Cargo_Delivery_Location', StringType(), True, {}),
        StructField('Cargo_Reference', StringType(), True, {}),
        StructField('Titan_Strategy', StringType(), True, {}),
        StructField('Liquid_Window', StringType(), True, {}),
        StructField('Run_Datetime', TimestampType(), True, {}),
        StructField('RefData_Datetime', TimestampType(), True, {}),
])
